name: deploy

on:
  push:
    branches: [ "main" ] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: Install and Build
        run: npm install && npm run build 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: ./dist
          github_token: ${{ secrets.TEST_CODE}}
          commit_message: Update Vite2.x + Vue3.x + TypeScript Starter
